package apresentacao;

import modelo.Controle;
import modelo.GerenciadorDeArquivos;
import modelo.GerenciadorDeLista;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmteste
     *
     * @param parent
     * @param modal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txfLocalLista = new javax.swing.JTextField();
        btnCarregar = new javax.swing.JButton();
        lblBubble = new javax.swing.JLabel();
        lblTempoBubble = new javax.swing.JLabel();
        lblTrocasBubble = new javax.swing.JLabel();
        lblTextInsertion = new javax.swing.JLabel();
        lblTempoInsert = new javax.swing.JLabel();
        lblTrocasInsert = new javax.swing.JLabel();
        Divisor = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblTempoQuick = new javax.swing.JLabel();
        lblTrocasQuick = new javax.swing.JLabel();
        btnExecutar = new javax.swing.JButton();
        Divisor_baixo = new javax.swing.JSeparator();
        btnGerar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblTamanho = new javax.swing.JLabel();
        txfTamanho = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        checkSalvar = new javax.swing.JCheckBox();
        lblLocalSalva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ferramenta para ordenação de dados");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocationByPlatform(true);
        setName("ferramentadetestes"); // NOI18N

        txfLocalLista.setEditable(false);
        txfLocalLista.setMinimumSize(new java.awt.Dimension(4, 24));
        txfLocalLista.setPreferredSize(new java.awt.Dimension(4, 24));

        btnCarregar.setText("Carregar lista...");
        btnCarregar.setToolTipText("Selecione a localização da lista que deseja ordenar");
        btnCarregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCarregarActionPerformed(evt);
            }
        });

        lblBubble.setText("BUBBLE SORT");

        lblTempoBubble.setText("Tempo: ");

        lblTrocasBubble.setText("Trocas:");

        lblTextInsertion.setText("INSERTION SORT");

        lblTempoInsert.setText("Tempo: ");

        lblTrocasInsert.setText("Trocas:");

        jLabel7.setText("QUICK SORT");

        lblTempoQuick.setText("Tempo: ");

        lblTrocasQuick.setText("Trocas:");

        btnExecutar.setText("Executar testes");
        btnExecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExecutar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExecutarActionPerformed(evt);
            }
        });

        btnGerar.setText("Gerar lista...");
        btnGerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel10.setText("Gerenciar lista:");

        lblTamanho.setText("Tamanho:");

        lblNome.setText("Nome:");

        txfNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        checkSalvar.setText("Salvar listas");
        checkSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Divisor)
            .addComponent(Divisor_baixo)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txfLocalLista, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarregar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBubble)
                            .addComponent(lblTempoBubble)
                            .addComponent(lblTrocasBubble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblTempoQuick)
                            .addComponent(lblTrocasQuick))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextInsertion)
                            .addComponent(lblTempoInsert)
                            .addComponent(lblTrocasInsert))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTamanho)
                                .addGap(6, 6, 6)
                                .addComponent(txfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGerar)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnExecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkSalvar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLocalSalva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfLocalLista, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Divisor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblBubble)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTempoBubble)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTrocasBubble))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblTextInsertion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTempoInsert)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTrocasInsert)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTempoQuick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTrocasQuick)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExecutar)
                    .addComponent(checkSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Divisor_baixo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerar)
                    .addComponent(lblTamanho)
                    .addComponent(txfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblLocalSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCarregar.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCarregarActionPerformed
    {//GEN-HEADEREND:event_btnCarregarActionPerformed
        GerenciadorDeArquivos Garc = new GerenciadorDeArquivos();
        String local;
        try
        {
            local = Garc.CarregarArquivo();
            if (local != null)
            {
                txfLocalLista.setText(local);
            }

        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGerarActionPerformed
    {//GEN-HEADEREND:event_btnGerarActionPerformed
        Controle ctr = new Controle();

        if (ctr.GerarLista(txfTamanho.getText(), txfNome.getText()))
        {
            txfLocalLista.setText(ctr.diretorioInteiro);
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        GerenciadorDeLista Glista;
        Glista = new GerenciadorDeLista();

        if (Glista.Ler(txfLocalLista.getText()) != null)
        {
            Controle ctr = new Controle();

            ctr.ExeTestes(txfLocalLista.getText());

            lblTempoBubble.setText("Tempo(ms): " + ctr.getTempoBubble());
            lblTrocasBubble.setText("Trocas: " + ctr.getTrocaBubble());

            lblTempoQuick.setText("Tempo(ms): " + ctr.getTempoQuick());
            lblTrocasQuick.setText("Trocas: " + ctr.getTrocaQuick());

            lblTempoInsert.setText("Tempo(ms): " + ctr.getTempoInsert());
            lblTrocasInsert.setText("Trocas: " + ctr.getTrocaInsert());

            ctr.ExibirResultados();

            if (checkSalvar.isSelected())
            {
                String[] listaordenadaBubble = ctr.getVetorBubble();
                String[] listaordenadaQuick = ctr.getVetorQuick();
                String[] listaordenadaInsert = ctr.getVetorInsert();

                ctr.SalvarListas(listaordenadaBubble, listaordenadaQuick, listaordenadaInsert);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Não foi possivel ler o arquivo !");
        }
    }//GEN-LAST:event_btnExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Divisor;
    private javax.swing.JSeparator Divisor_baixo;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnGerar;
    private javax.swing.JCheckBox checkSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBubble;
    private javax.swing.JLabel lblLocalSalva;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTempoBubble;
    private javax.swing.JLabel lblTempoInsert;
    private javax.swing.JLabel lblTempoQuick;
    private javax.swing.JLabel lblTextInsertion;
    private javax.swing.JLabel lblTrocasBubble;
    private javax.swing.JLabel lblTrocasInsert;
    private javax.swing.JLabel lblTrocasQuick;
    private javax.swing.JTextField txfLocalLista;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfTamanho;
    // End of variables declaration//GEN-END:variables
}
